model_params:
  name: 'CategoricalVAE'
  in_channels: 1
  latent_dim: 10
  categorical_dim: 33
  temperature: 0.5
  anneal_rate: 0.00003
  anneal_interval: 100
  alpha: 1.0
  init: uniform
  activation: relu

exp_params:
  dataset: TCGA
  data_path: "./Data/rna"
  batch_size: 64 # Better to have a square number
  LR: 0.001
  weight_decay: 0.0
  scheduler_gamma: 0.95
  optimizer: Adam
  train_size: 0.7
  test_size: 0

trainer_params:
  #gpus: [1]
  max_epochs: 10000

logging_params:
  save_dir: "logs/"
  name: "CategoricalVAE"
  manual_seed: 1265
