model_params:
  name: 'LogCoshVAE'
  in_channels: 1
  latent_dim: 200
  init: uniform
  alpha: 10.0
  beta: 1.0

exp_params:
  dataset: TCGA
  data_path: "./Data/rna"
  batch_size: 64 # Better to have a square number
  LR: 0.0001
  weight_decay: 0.0
  scheduler_gamma: 0.97
  optimizer: Adam
  train_size: 0.7
  test_size: 0

trainer_params:
  #gpus: [2]
  max_epochs: 1000

logging_params:
  save_dir: "logs/"
  name: "LogCoshVAE"
  manual_seed: 1265
